### ISSUE TITLE
Don't include password in Java Opts

### ISSUE THREAD

**Issue by absa-piotr-andruszkiewicz** [wttech/aemc#150]
Hello,

Right now, the admin password for the newly created instance is provided via `admin.password` property.

Rel: https://github.com/wttech/aemc/blob/b33ddaf8fc98c595668d07dc8d5c91fb0c661417/pkg/local_instance.go#L835

I think it should be provided via `admin.password.file` property, so that it cannot be read from `ps uax` output.

Ref: https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/security-configure-admin-password.html?lang=en#using-the-nointeractive-flag

We would need to make sure that such temporary password file is created with restrictive umask and deleted right after use.

**Comment by krystian-panek-wttech** [comment]
Good one. But adds complexity. Don't hesitate to implement it

**Comment by piotr-andruszkiewicz-wttech** [comment]
Done in https://github.com/wttech/aemc/pull/193

**Comment by krystian-panek-wttech** [comment]
thanks @piotr-andruszkiewicz-wttech
