### ISSUE TITLE
Use status command to check if instance is up-to-date

### ISSUE THREAD

**Issue by jan-kowalczyk-wttech** [wttech/aemc#152]
Currently there is no command to check, if configuration of aem has changed (for example in aem.yml).
We can use status command to check, if something has changed.

**Comment by krystian-panek-wttech** [comment]
by "configuration" you rather mean specific AEM instance details like HTTP port, Sling run modes, password, JVM/start opts - the things that may cause the instance to restart.

yep, that may help to bubble up that info to the systemd so that it need to restart AEM service

**Comment by krystian-panek-wttech** [comment]
@jan-kowalczyk-wttech It should be pretty easy to implement, don't hesitate to do it ;)
