### ISSUE TITLE
sh taskw start fails (due to regression in latest Docker version?)

### ISSUE THREAD

**Issue by jakub-przybytek-wttech** [wttech/aemc#237]
Hi, when I do `sh taskw start` I got eventually this error:
```
task: [dispatcher:start] docker tag "$(docker load --input "home/sdk/lib/dispatcher-publish-amd64.tar.gz" | awk -v 'FS= ' '{print $3}')" "adobe/aem-ethos/dispatcher-publish:latest"
Error parsing reference: "get\nadobe/aem-cs/dispatcher-publish:2.0.193" is not a valid repository/tag: invalid reference format
task: Failed to run task "start": exit status 1
```
It may be related to my version of docker:
```
λ docker --version
Docker version 25.0.3, build 4debf41
```
as, when I do `docker load --input "dispatcher/home/sdk/lib/dispatcher-publish-amd64.tar.gz > output_file` I get the follwoing:
```
failed to get console mode for stdout: The handle is invalid.
Loaded image: adobe/aem-cs/dispatcher-publish:2.0.193 
```
Because I am getting two lines, resulting tag name is "get\nadobe/aem-cs/dispatcher-publish:2.0.193".
'failed to get...' might be some kind of regression from latest versions of docker... not sure

**Comment by krystian-panek-wttech** [comment]
done
