### ISSUE TITLE
Generate .gitignore

### ISSUE THREAD

**Issue by maciej-majchrzak-wttech** [wttech/aemc#84]
`project-init.sh` should generate .gitignore file so that you don't need to figure it out which files should be pushed to git
Initial .gitignore can be as simple as
```
aem/home
dispatcher/target
```

**Comment by krystian-panek-wttech** [comment]
Usually ignore file exist so these line's need to be appended

**Comment by maciej-majchrzak-wttech** [comment]
Yup, that's right - I've updated my PR to reflect this

**Comment by krystian-panek-wttech** [comment]
todo: .env file should be VCS-ignored as well. but aem.env and local.env not

**Comment by krystian-panek-wttech** [comment]
covered in https://github.com/wttech/aemc/blob/main/pkg/project/project.go#L151
